/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  ipWhitelist: [],
  language: 'uk',
  modules: [
    {
      module: 'alert',
      header: '',
      config: {}
    },
    {
      module: 'MMM-ImageSlideshow',
      position: 'lower_third',
      config: {
        imagePaths: ['modules/MMM-ImageSlideshow/example1']
      }
    },
    // {
    //     module: 'MMM-ip',
    //     position: 'top_right', // Remove the position if you want to run the module in voice only mode
    //     config: {
    //       families: ['IPv4'],
    //       fontSize: 5,
    //         // all your config options, which are different than their default values
    //     }
    // },
    {
      module: 'clock',
      position: 'top_left',
      header: '',
      config: {
        timezone: 'Europe/Kyiv'
      }
    },
    {
      module: 'compliments',
      position: 'bottom_bar',
      header: '',
      config: {
        compliments: {
          anytime: [
            'Привіт найкраща!',
            'Ти все зможеш!',
            'В тебе вистачить сил на твої ідеї!',
            'Вірю в тебе!',
            'Ти маєш право бачити свої сильні сторони.',
            'Твоєму тілу можна довіряти.',
            'Дай собі час.'
          ],
          morning: [
            'Привітик сонечко!',
            'Приємного дня!',
            'Гарно спалось?'
          ],
          afternoon: [
            'Привіт неповторна людино!',
            'Гарно виглядаєш',
            'Ти просто бімба!'
          ],
          evening: [
            'Дивлюсь на гаряченьке!',
            'Ти просто скарб!',
            'Вірю в тебе!'
          ],
          '....-01-01': [
            'Happy new year!'
          ]
        }
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: '',
      config: {
        location: 'Uzhgorod',
        locationID: '690548',
        apiKey: '295f1213579bc06656d8c2b4ed75ef8c',
        lang: 'ua'
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: 'Weather Forecast',
      config: {
        type: 'forecast',
        location: 'Uzhgorod',
        locationID: '690548',
        apiKey: '295f1213579bc06656d8c2b4ed75ef8c',
        lang: 'ua'
      }
    },
    // {
    //   module: 'MMM-Remote-Control',
    //   config: {
    //     showModuleApiMenu: true,
    //     secureEndpoints: true
    //   }
    // },
    // {
    //   module: 'MMM-Screencast',
    //   position: 'bottom_right',
    //   config: {
    //     position: 'bottomRight',
    //     height: 480,
    //     width: 640
    //   }
    // }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  locale: 'ua-UA'
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
